### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by BlueWeabo** [BlueWeabo/MuTECore#1]
- [x] Do sample rendering
- [x] Integrate an item inventory
- [x] Integrate a fluid inventory
- [x] Make a sample GUI
- [x] Make a sample system
- [x] Add event for block breaking
- [x] Add event for block placing
- [x] Add event for neighbor updates
